### PR TITLE
:sparkles: [Feature] Add `customHTML` attirubte.

### PR DESCRIPTION
**Pull request by oinochoe**
I feel there are a lot of limitations in modifying the style of electron-progressbar or loading fonts, so is it possible to add a customHTML property?

### CODE REVIEW

**Comment by AndersonMamede** [comment]
Hi @oinochoe , the new feature looks great! I'm merging it, and since it's backward compatible, I'll release it under v2.2.0. Thank you very much for the contribution! :)

**Comment by AndersonMamede** [comment]
Update: v2.2.0 has been released with this feature.

@oinochoe once again, thanks for the contribution!

**Comment by oinochoe** [comment]
> Update: v2.2.0 has been released with this feature.
> 
> @oinochoe once again, thanks for the contribution!

Hi, @AndersonMamede  I'm sorry, but I found a typo. I'll edit it again and get the PR up quickly.
😅

**Comment by AndersonMamede** [comment]
@oinochoe no worries! I'm merging and releasing #44. Thanks for the fix!

**Pull request merged**
